// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-VMIVAf114km7D-oaP9ouKoMU9yrlo4A',
    appId: '1:568693278515:web:3b795b723beaff77f4a046',
    messagingSenderId: '568693278515',
    projectId: 'coffeebox-4d267',
    authDomain: 'coffeebox-4d267.firebaseapp.com',
    storageBucket: 'coffeebox-4d267.appspot.com',
    measurementId: 'G-WB9XTY5LLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsT6Aw5o9ZXcJiB-FvAAkgYG71WqQ-wT4',
    appId: '1:568693278515:android:51a7def4caa28f01f4a046',
    messagingSenderId: '568693278515',
    projectId: 'coffeebox-4d267',
    storageBucket: 'coffeebox-4d267.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXkNZiwb93dzem8d3-dF8GAxqD8yng1A0',
    appId: '1:568693278515:ios:3a1b0c327907b9f9f4a046',
    messagingSenderId: '568693278515',
    projectId: 'coffeebox-4d267',
    storageBucket: 'coffeebox-4d267.appspot.com',
    iosClientId: '568693278515-eccs9goom7qq10frolbc7i08e8ff2h7l.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeBox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXkNZiwb93dzem8d3-dF8GAxqD8yng1A0',
    appId: '1:568693278515:ios:3a1b0c327907b9f9f4a046',
    messagingSenderId: '568693278515',
    projectId: 'coffeebox-4d267',
    storageBucket: 'coffeebox-4d267.appspot.com',
    iosClientId: '568693278515-eccs9goom7qq10frolbc7i08e8ff2h7l.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeBox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-VMIVAf114km7D-oaP9ouKoMU9yrlo4A',
    appId: '1:568693278515:web:6fdca314068b0aaaf4a046',
    messagingSenderId: '568693278515',
    projectId: 'coffeebox-4d267',
    authDomain: 'coffeebox-4d267.firebaseapp.com',
    storageBucket: 'coffeebox-4d267.appspot.com',
    measurementId: 'G-XPYRQ1YRBS',
  );
}
