spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

square.access.token=EAAAlzARU7BKqsSZckFvvcflfq9Mam1KBLj-XuRC16nsoGBcQgqg_mnUXy28ZIYA
square.application.id=sandbox-sq0idb-FrwHUoe3HJ64LYMoOJdUaQ
square.location.id=L1XAR3WTHCT5S
square.environment=sandbox
